alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias p='cd -'
alias md='mkdir'
alias cd..="cd .."
alias realias="source $HOME/.bash_aliases"
alias refunc="source $HOME/.bash_functions"
#alias pbcopy='xclip -selection clipboard'
#alias pbpaste='xclip -selection clipboard -o'
